# Generated by Django 5.0.3 on 2025-08-06 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contribution_type', models.CharField(choices=[('code', 'Code'), ('bug', 'Bug Fix'), ('docs', 'Documentation'), ('forum', 'Forum Support'), ('mentoring', 'Mentoring'), ('community', 'Community Help'), ('resume', 'Resume Creation (AI)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
