# Generated by Django 5.0.3 on 2025-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='proof_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('code', 'Code'), ('bugfix', 'Bug Fix'), ('docs', 'Documentation'), ('mentorship', 'Mentorship'), ('resume', 'Resume Generator'), ('community', 'Community Help'), ('codereview', 'Code Review')], max_length=32),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
