# Generated by Django 5.0.3 on 2025-08-18 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_contributionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributionrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contributionrequest',
            name='via_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contributionrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributionrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='contributionrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contributionrequest',
            name='message',
        ),
    ]
