# Generated by Django 5.0.3 on 2025-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_alter_contributionrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionrequest',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
