# Generated by Django 5.0.3 on 2025-08-20 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_contributionrequest_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
