# Generated by Django 5.0.3 on 2025-08-14 07:34

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringvideo',
            name='video_file',
            field=models.FileField(upload_to=videos.models.mentoring_video_upload_path),
        ),
    ]
