# Generated by Django 5.0.3 on 2025-08-12 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contribution_is_public_contribution_proof_url_and_more'),
        ('endorsements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endorsement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='contributions.contribution'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='endorsed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='endorsed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='endorsement',
            unique_together={('endorsed_user', 'endorsed_by', 'contribution')},
        ),
    ]
