# Generated by Django 5.0.3 on 2025-08-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GitHub Username'),
        ),
    ]
